# Generated by Django 3.2.5 on 2021-07-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('C', 'Customer'), ('M', 'Merchant')], default='C', max_length=1),
        ),
    ]
