# Generated by Django 3.2.5 on 2021-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_shop_owner',
            field=models.BooleanField(default=False),
        ),
    ]
