# Generated by Django 3.2.6 on 2021-08-29 02:05

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_updated_item_field'),
        ('users', '0004_added_preference_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='search_modifier',
            field=models.PositiveSmallIntegerField(default=0, validators=[users.validators.validate_preference_search_modifier]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user_value',
            field=models.PositiveSmallIntegerField(default=1, validators=[users.validators.validate_preference_value]),
        ),
    ]
