version: '3.9'

services:
    web:
        container_name: web
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn mercator.wsgi -b 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=django-insecure-6t_7y*p&cpac2@)rlgw01rc!)&y$h2quq^l-9!6tfzgxf@*u21"
            - "DJANGO_DEBUG=True"
            - "DJANGO_SECURE_SSL_REDIRECT=False"
            - "DJANGO_SECURE_HSTS_SECONDS=0"
            - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
            - "DJANGO_SECURE_HSTS_PRELOAD=False"
            - "DJANGO_SESSION_COOKIE_SECURE=False"
            - "DJANGO_CSRF_COOKIE_SECURE=False"

    db:
        container_name: db
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            
volumes:
    postgres_data:
