version: '3.9'

services:
    web:
        build: .
        command: python /mercator/manage,py runserver 0.0.0.0
        volumes:
        - .:/mercator
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:11
        volumes:
            - /var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        # This will probably affect the db writing
        # volumes:
        #     postgres_data:
