# Generated by Django 3.2.5 on 2021-07-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default_product.png', upload_to='images/'),
        ),
    ]
