# Generated by Django 3.2.5 on 2021-07-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_and_shopStyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='style',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopstyle'),
        ),
    ]
