# Generated by Django 3.2.5 on 2021-07-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_updated_shop_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products_sold', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(choices=[('P', 'Product'), ('S', 'Shop')], max_length=1)),
                ('model_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopstyle',
            name='background_style',
            field=models.CharField(choices=[('C', 'Color'), ('I', 'Image')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='analytics',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopanalytics'),
        ),
    ]
