# Generated by Django 3.2.6 on 2021-08-13 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210806_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='analytics',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopanalytics'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='style',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopstyle'),
        ),
    ]
