# Generated by Django 3.2.6 on 2021-08-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_fixed_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='country',
            field=models.CharField(default='N/A', max_length=40),
            preserve_default=False,
        ),
    ]
