# Generated by Django 3.2.6 on 2021-08-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_item_wrapper_for_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='in_carts', to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('ML', 'Mail'), ('PD', 'Parcel Delivery Company'), ('JB', 'Jeff Bezos with a bicycle (cheapest)')], default='ML', max_length=2),
        ),
    ]
