# Generated by Django 3.2.6 on 2021-08-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_refactored_cart_order_item'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='product',
        ),
    ]
