# Generated by Django 3.2.6 on 2021-08-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_refactored_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['product']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to=None,
        ),
    ]
