# Generated by Django 3.2.6 on 2021-08-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_refactored_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
