# Generated by Django 3.2.6 on 2021-09-03 13:09

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_changing_review_fk_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(default=3, validators=[shop.validators.validate_review_stars]),
        ),
    ]
