name: Django tests with Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id : buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mercator:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django pillow
      
      - name: Run tests
        run: docker-compose exec web python manage.py test
